---
# Copyright (C) 2024 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2020 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart influxdb2 service
  ansible.builtin.systemd:
    name: 'influxdb.service'
    state: 'restarted'
