---
# Copyright (C) 2024 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2024 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Import DebOps global handlers
  ansible.builtin.import_role:
    name: 'global_handlers'

- name: Import DebOps secret role
  ansible.builtin.import_role:
    name: 'secret'

- name: Enable and start InfluxDBv2 service
  ansible.builtin.systemd:
    name: 'influxdb.service'
    state: 'started'
    enabled: True

- name: Configure InfluxDBv2 server
  ansible.builtin.template:
    src: 'etc/influxdb/config.toml.j2'
    dest: '/etc/influxdb/config.toml'
    mode: '0644'
  tags: [ 'role::influxdb2:config' ]
  notify: [ 'Restart influxdb2 service' ]

- name: Make sure that Ansible local facts directory exists
  ansible.builtin.file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    mode: '0755'

- name: Save InfluxDBv2 server local facts
  ansible.builtin.template:
    src: 'etc/ansible/facts.d/influxdb2.fact.j2'
    dest: '/etc/ansible/facts.d/influxdb2.fact'
    mode: '0755'
  notify: [ 'Refresh host facts' ]
  tags: [ 'meta::facts' ]

- name: Re-read local facts if they have been modified
  ansible.builtin.meta: 'flush_handlers'
