---
# Copyright (C) 2023 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Create a "bond1" network devie and add two Ethernet devices to it. Configure
# the IPv6 networking using DHCP.

# File: ansible/inventory/host_vars/hostname/networkd.yml

networkd__host_units:

  - name: '30-bond1.network'
    raw: |
      [Match]
      Name=bond1

      [Network]
      DHCP=ipv6
    state: 'present'

  - name: '30-bond1.netdev'
    raw: |
      [NetDev]
      Name=bond1
      Kind=bond
    state: 'present'

  - name: '30-bond1-dev1.network'
    raw: |
      [Match]
      MACAddress=52:54:00:e9:64:41

      [Network]
      Bond=bond1
    state: 'present'

  - name: '30-bond1-dev2.network'
    raw: |
      [Match]
      MACAddress=52:54:00:e9:64:42

      [Network]
      Bond=bond1
    state: 'present'
